### ISSUE TITLE
3rd party libraries don't override built-ins

### ISSUE THREAD

**Issue by webmaven** [GoogleCloudPlatform/appengine-flask-skeleton#10]
Built in libraries are used even when 3rd-party libraries should override them. For example, WebOb 1.4 vs. the built-in 1.2.

This problem was inadvertently introduced with https://github.com/GoogleCloudPlatform/appengine-python-flask-skeleton/pull/9

**Comment by jonparrott** [comment]
We use vendor now, so this shouldn't be a problem.

**Comment by webmaven** [comment]
:+1:
