### ISSUE TITLE
How to use endpoints with flask and gae?

### ISSUE THREAD

**Issue by du2x** [GoogleCloudPlatform/appengine-flask-skeleton#19]
I missed the use of endpoints in this skeleton.
According to Google and Udacity course, the endpoints are a major functionally.

**Comment by jonparrott** [comment]
Hi @du2x, I noticed you closed this. Did you get your question answered?

**Comment by du2x** [comment]
No. Actually, I closed it because I was not sure about putting here as a issue is appropriate.
But I found a repo that can help me: https://github.com/Eforcers/gae-flask-todo.
Furthermore, after seeing that repo, I see that maybe the use of endpoints with flask be a new skelleton, since there is much code to add.

**Comment by jonparrott** [comment]
You can think of cloud endpoints as essentially a separate WSGI app that lives alongside your flask app. They can share common code, but the "web framework" part is different. It's like using Flask and Bottle side-by-side. It's possible, but a little tricky.

Your `app.yaml` would likely look something like this:

```yaml
handlers:
# Endpoints handler.
- url: /_ah/spi/.*
  script: api.APPLICATION

# Flask handler
- url: /.*
  script :main.app
```

`api.py` would contain the normal endpoints stuff, and define `APPLICATION` like this:

```
APPLICATION = endpoints.api_server([HelloWorldApi])
```

`main.py` would just be a regular flask app that defines `app`:

```
app = Flask(__name__)
```

**Comment by du2x** [comment]
nice, it's pretty clear now.
thanks @jonparrott .

**Comment by jonparrott** [comment]
No problem, glad I could help.
