### ISSUE TITLE
pip install line from README fails because "lib" already exists in repo

### ISSUE THREAD

**Issue by thundergolfer** [GoogleCloudPlatform/appengine-flask-skeleton#25]
1. Install App Engine Python SDK
2. Clone the repo in the README
3. 'cd appengine-python-flask-skeleton'
4. 'pip install -r requirements.txt -t lib'

Command fails because lib already contains the dependencies. Wouldn't it be better to specify something like `pip install --upgrade -r requirements.txt` in the README?

**Comment by waprin** [comment]
The command doesn't fail for me on OS X, pip 8.1.2 . Can you provide more details about your version of pip, Python, OS  etc?

There's also no real need to --upgrade since we're pinning the dependencies anyway.

@thundergolfer

**Comment by waprin** [comment]
I do see some warnings, but they are just that, warnings. Don't see a need to force replacement given we're pinning dependencies.

I agree it's strange to pre-vendor the dependencies. The reason we do it for these projects is they are used in quickstarts where the repo is directly downloaded, and where we say "just clone then do appcfg.py update", and people don't necessarily see the README.

**Comment by waprin** [comment]
Will re-open if you have any more comments.
